# Generated by Django 2.2.11 on 2020-03-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'District Types',
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Facility Types',
            },
        ),
        migrations.CreateModel(
            name='ICD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('option', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ICD10 Codes',
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Location Types',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OPDEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('age_in_days', models.IntegerField()),
                ('age_in_months', models.IntegerField()),
                ('age_in_years', models.IntegerField()),
                ('report_date', models.DateField(auto_now_add=True)),
                ('data_of_attendance', models.DateField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(max_length=1)),
                ('referred_from', models.CharField(blank=True, max_length=120)),
                ('referred_to', models.CharField(blank=True, max_length=120)),
                ('event_completed', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.ICD10')),
                ('other_diagnosis', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_diagnosis', to='app.ICD10')),
                ('secondary_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_diagnosis', to='app.ICD10')),
            ],
            options={
                'verbose_name_plural': 'OPD 1st Attendance Events',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DHIS2_UID', models.CharField(blank=True, max_length=13, null=True)),
                ('HMIS_code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=254, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.District')),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.FacilityType')),
                ('location_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.LocationType')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='district_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.DistrictType'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Province'),
        ),
    ]
