# Generated by Django 2.2.11 on 2020-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200320_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icd10',
            name='name',
        ),
        migrations.RemoveField(
            model_name='icd10',
            name='option',
        ),
        migrations.AddField(
            model_name='icd10',
            name='description',
            field=models.CharField(default='', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
