# Generated by Django 2.2.11 on 2020-03-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200322_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_type',
        ),
        migrations.DeleteModel(
            name='DistrictType',
        ),
    ]
