# Generated by Django 2.2.11 on 2020-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200322_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='HMIS_code',
        ),
        migrations.AlterField(
            model_name='icd10',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='icd10',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='icd10',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
