# Generated by Django 2.2.11 on 2020-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200322_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdevent',
            name='diagnosis',
            field=models.CharField(max_length=100),
        ),
    ]
