# Generated by Django 2.2.11 on 2020-03-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200328_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdevent',
            name='other_diagnosis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opdevent',
            name='secondary_diagnosis',
            field=models.CharField(max_length=100),
        ),
    ]
