# Generated by Django 2.2.11 on 2020-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2_ICD10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'DHIS2 ICD10 Codes',
            },
        ),
        migrations.AlterField(
            model_name='ipdevent',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ipdevent',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ipdevent',
            name='other_diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ipdevent',
            name='secondary_diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opdevent',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='opdevent',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='opdevent',
            name='other_diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opdevent',
            name='secondary_diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
